# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: This too shall pass... 
email: USER @ iki.fi
description: > # this means to ignore newlines until "baseurl:"
   All kinds of writings, notes and hints for stuff that needs a web location.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  tuulap

# Build settings
markdown: kramdown
